### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rabiu42000** [anyoptimization/pysamoo#1] opened 2022-05-05 22:25 UTC
How do i access pymoo>0.5.0. I get the error below when installing pysamoo

ERROR: Could not find a version that satisfies the requirement pymoo>0.5.0 (from pysamoo) (from versions: 0.1.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.2.1, 0.4.2.2rc2, 0.4.2.2, 0.5.0, 0.6.0.dev0)
ERROR: No matching distribution found for pymoo>0.5.0

**Comment by Ferreira-B** [comment] 2022-05-23 10:54
Hey, I get the same error.

**Comment by mohamedzayyan** [comment] 2022-06-02 16:02
Hi
I had the same error when trying to run `pip install pysamoo`, but I was able to install pysamoo by downloading the source files (either from this repo or from [pypi](https://pypi.org/project/pysamoo/#files) and running `python setup.py install`
However, I am then get an AttributeError stating `AttributeError: 'ZDT1' object has no attribute 'n_ieq_constr'` when trying to run any of the pysamoo examples. Could you try to install this way and see if you can reproduce the error? Or if it works for you?

**Comment by rabiu42000** [comment] 2022-06-02 16:21
I get the same error: AttributeError: 'ZDT1' object has no attribute 'n_ieq_constr'

**Comment by mohamedzayyan** [comment] 2022-06-02 16:44
Interesting. Thanks for your reply. I am still investigating what could be the cause. I have also reached out to Julian to see if he has any ideas as to why we are receiving this error. I will keep you updated.

**Comment by mohamedzayyan** [comment] 2022-06-09 10:08
Hi 

After consulting with Julian, I have the solution. First uninstall any versions of pymoo and pysamoo that you may currently have. Then install the current pre-release version of pymoo `(pip install pymoo==0.6.0.dev0)`. Then you may run `pip install pysamoo`. After that, everything should be working fine.

**Comment by blankjul** [comment] 2022-12-12 02:51
Should be fixed now. Sorry for the inconvenience.

**Closed as completed by blankjul** 2022-12-12 02:51 UTC
